import type { RichGradeReport } from "@/lib/grade-flow-data";
import type { DashboardGrade } from "@/lib/dashboard-data";
import { SITE } from "@/lib/constants";

function slugify(name: string) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 48);
}

export function reportShareUrl(gradeId: string) {
  if (typeof window === "undefined") {
    return `${SITE.url}/dashboard?report=${encodeURIComponent(gradeId)}`;
  }
  const url = new URL("/dashboard", window.location.origin);
  url.searchParams.set("report", gradeId);
  return url.toString();
}

export function reportSummaryText(report: RichGradeReport) {
  const g = report.grade;
  return [
    `${g.name} — GemMint AI Grade Report`,
    `${g.year} · ${g.set} · ${g.category}`,
    `PSA ${g.psa} · Beckett ${g.beckett} · ${g.confidence}% confidence`,
    `Est. value: $${g.estimatedValue.toLocaleString()}`,
    `Recommendation: ${g.recommendation}`,
    report.explanation,
    reportShareUrl(g.id),
  ].join("\n");
}

export function reportHtmlDocument(report: RichGradeReport) {
  const g = report.grade;
  const img = g.imageUrl
    ? `<img src="${g.imageUrl}" alt="${escapeHtml(g.name)}" style="width:180px;border-radius:12px;border:1px solid #e5e7eb;" />`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(g.name)} · GemMint Report</title>
  <style>
    body { font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, sans-serif; color: #111827; margin: 0; padding: 32px; background: #fff; }
    h1 { font-size: 28px; margin: 0 0 4px; }
    .muted { color: #6b7280; font-size: 14px; }
    .grid { display: grid; grid-template-columns: 180px 1fr; gap: 24px; margin-top: 24px; }
    .pill { display: inline-block; padding: 6px 10px; border-radius: 8px; background: #ecfdf5; color: #15803d; font-weight: 700; font-size: 13px; margin-right: 8px; }
    .pill.blue { background: #eff6ff; color: #1d4ed8; }
    .card { border: 1px solid #e5e7eb; border-radius: 16px; padding: 16px; margin-top: 16px; }
    .row { display: flex; justify-content: space-between; gap: 12px; padding: 8px 0; border-bottom: 1px solid #f3f4f6; font-size: 14px; }
    .row:last-child { border-bottom: 0; }
    @media print { body { padding: 12px; } }
  </style>
</head>
<body>
  <p class="muted" style="font-weight:600;letter-spacing:.06em;text-transform:uppercase;color:#16a34a;">GemMint AI Grading Report</p>
  <h1>${escapeHtml(g.name)}</h1>
  <p class="muted">${escapeHtml(`${g.year} · ${g.set} · ${g.category}`)}</p>
  <div class="grid">
    <div>${img}</div>
    <div>
      <span class="pill">PSA ${g.psa}</span>
      <span class="pill blue">BGS ${escapeHtml(g.beckett)}</span>
      <p style="margin-top:16px;line-height:1.5;">${escapeHtml(report.explanation)}</p>
      <div class="card">
        <div class="row"><span>Confidence</span><strong>${g.confidence}%</strong></div>
        <div class="row"><span>Estimated value</span><strong>$${g.estimatedValue.toLocaleString()}</strong></div>
        <div class="row"><span>Recommendation</span><strong>${escapeHtml(g.recommendation)}</strong></div>
        <div class="row"><span>Centering</span><strong>${escapeHtml(g.centering.lr)} / ${escapeHtml(g.centering.tb)}</strong></div>
        <div class="row"><span>Corners</span><strong>${g.corners.scores.join(" · ")}</strong></div>
        <div class="row"><span>Edges</span><strong>${g.edges.score}/10</strong></div>
        <div class="row"><span>Surface</span><strong>${g.surface.score}/10</strong></div>
        <div class="row"><span>Market (raw → PSA 10)</span><strong>$${g.market.raw} → $${g.market.psa10}</strong></div>
      </div>
    </div>
  </div>
  <p class="muted" style="margin-top:28px;">Generated by GemMint · ${escapeHtml(g.date)}</p>
</body>
</html>`;
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function triggerDownload(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.rel = "noopener";
  document.body.appendChild(a);
  a.click();
  a.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1500);
}

export function downloadReportPdf(report: RichGradeReport) {
  const html = reportHtmlDocument(report);
  const w = window.open("", "_blank", "noopener,noreferrer,width=900,height=1000");
  if (!w) {
    // Popup blocked — fall back to downloading an HTML report
    downloadReportFile(report, "html");
    return { mode: "file" as const };
  }
  w.document.open();
  w.document.write(html);
  w.document.close();
  // Give images a moment to paint, then open the print dialog (Save as PDF)
  window.setTimeout(() => {
    w.focus();
    w.print();
  }, 350);
  return { mode: "print" as const };
}

export function downloadReportFile(
  report: RichGradeReport,
  format: "html" | "json" = "html"
) {
  const base = `gemmint-${slugify(report.grade.name) || "report"}-${report.grade.id.slice(0, 8)}`;
  if (format === "json") {
    triggerDownload(
      `${base}.json`,
      new Blob([JSON.stringify(report, null, 2)], { type: "application/json" })
    );
    return;
  }
  triggerDownload(
    `${base}.html`,
    new Blob([reportHtmlDocument(report)], { type: "text/html;charset=utf-8" })
  );
}

export async function shareReport(report: RichGradeReport) {
  const url = reportShareUrl(report.grade.id);
  const title = `${report.grade.name} · GemMint Report`;
  const text = reportSummaryText(report);

  if (typeof navigator !== "undefined" && typeof navigator.share === "function") {
    try {
      await navigator.share({ title, text, url });
      return { mode: "native" as const };
    } catch (err) {
      // User cancelled share sheet
      if (err instanceof DOMException && err.name === "AbortError") {
        return { mode: "cancelled" as const };
      }
    }
  }

  await navigator.clipboard.writeText(`${text}\n${url}`);
  return { mode: "clipboard" as const };
}

export async function copyReportLink(grade: DashboardGrade | { id: string }) {
  const url = reportShareUrl(grade.id);
  await navigator.clipboard.writeText(url);
  return url;
}
